#ifndef UPNPHTTPHEADERS_H
#define UPNPHTTPHEADERS_H

/*!
 * \file
 *
 * \brief Header file for UpnpHttpHeaders methods.
 *
 * Do not edit this file, it is automatically generated.
 * Please look at generator.c.
 *
 * \author Marcelo Roberto Jimenez
 */

/*!
 * UpnpHttpHeaders
 */
typedef struct s_UpnpHttpHeaders UpnpHttpHeaders;

#include "UpnpGlobal.h" /* for EXPORT_SPEC */
#include "UpnpString.h"
#include "ixml.h"
#include "list.h"

#include <stdlib.h> /* for size_t */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*! Constructor */
EXPORT_SPEC UpnpHttpHeaders *UpnpHttpHeaders_new();
/*! Destructor */
EXPORT_SPEC void UpnpHttpHeaders_delete(UpnpHttpHeaders *p);
/*! Copy Constructor */
EXPORT_SPEC UpnpHttpHeaders *UpnpHttpHeaders_dup(const UpnpHttpHeaders *p);
/*! Assignment operator */
EXPORT_SPEC int UpnpHttpHeaders_assign(
	UpnpHttpHeaders *p, const UpnpHttpHeaders *q);

/*! UpnpHttpHeaders_get_node */
EXPORT_SPEC const UpnpListHead *UpnpHttpHeaders_get_node(
	const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_set_node */
EXPORT_SPEC int UpnpHttpHeaders_set_node(
	UpnpHttpHeaders *p, const UpnpListHead *q);
/*! UpnpHttpHeaders_add_to_list_node */
EXPORT_SPEC void UpnpHttpHeaders_add_to_list_node(
	UpnpHttpHeaders *p, UpnpListHead *head);

/*! UpnpHttpHeaders_get_name */
EXPORT_SPEC const UpnpString *UpnpHttpHeaders_get_name(
	const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_set_name */
EXPORT_SPEC int UpnpHttpHeaders_set_name(
	UpnpHttpHeaders *p, const UpnpString *s);
/*! UpnpHttpHeaders_get_name_Length */
EXPORT_SPEC size_t UpnpHttpHeaders_get_name_Length(const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_get_name_cstr */
EXPORT_SPEC const char *UpnpHttpHeaders_get_name_cstr(const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_strcpy_name */
EXPORT_SPEC int UpnpHttpHeaders_strcpy_name(UpnpHttpHeaders *p, const char *s);
/*! UpnpHttpHeaders_strncpy_name */
EXPORT_SPEC int UpnpHttpHeaders_strncpy_name(
	UpnpHttpHeaders *p, const char *s, size_t n);
/*! UpnpHttpHeaders_clear_name */
EXPORT_SPEC void UpnpHttpHeaders_clear_name(UpnpHttpHeaders *p);

/*! UpnpHttpHeaders_get_value */
EXPORT_SPEC const UpnpString *UpnpHttpHeaders_get_value(
	const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_set_value */
EXPORT_SPEC int UpnpHttpHeaders_set_value(
	UpnpHttpHeaders *p, const UpnpString *s);
/*! UpnpHttpHeaders_get_value_Length */
EXPORT_SPEC size_t UpnpHttpHeaders_get_value_Length(const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_get_value_cstr */
EXPORT_SPEC const char *UpnpHttpHeaders_get_value_cstr(
	const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_strcpy_value */
EXPORT_SPEC int UpnpHttpHeaders_strcpy_value(UpnpHttpHeaders *p, const char *s);
/*! UpnpHttpHeaders_strncpy_value */
EXPORT_SPEC int UpnpHttpHeaders_strncpy_value(
	UpnpHttpHeaders *p, const char *s, size_t n);
/*! UpnpHttpHeaders_clear_value */
EXPORT_SPEC void UpnpHttpHeaders_clear_value(UpnpHttpHeaders *p);

/*! UpnpHttpHeaders_get_resp */
EXPORT_SPEC const DOMString UpnpHttpHeaders_get_resp(const UpnpHttpHeaders *p);
/*! UpnpHttpHeaders_set_resp */
EXPORT_SPEC int UpnpHttpHeaders_set_resp(UpnpHttpHeaders *p, const DOMString s);
/*! UpnpHttpHeaders_get_resp_cstr */
EXPORT_SPEC const char *UpnpHttpHeaders_get_resp_cstr(const UpnpHttpHeaders *p);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* UPNPHTTPHEADERS_H */
