cmake_minimum_required(VERSION 3.11)

project(fuzzer LANGUAGES C)
add_executable(FuzzIxml FuzzIxml.c)
add_executable(FuzzHttp FuzzHttp.c)
add_executable(FuzzServiceTable FuzzServiceTable.c)
add_executable(FuzzIxmlDom FuzzIxmlDom.c)
add_executable(FuzzIxmlOps FuzzIxmlOps.c)

target_link_libraries(FuzzIxml ixml_static ${LIB_FUZZING_ENGINE})
target_include_directories(FuzzHttp PRIVATE ${CMAKE_SOURCE_DIR}/upnp/src/threadutil)
target_link_libraries(FuzzHttp upnp_static ${LIB_FUZZING_ENGINE})
target_include_directories(FuzzServiceTable PRIVATE ${CMAKE_SOURCE_DIR}/upnp/src/threadutil)
target_link_libraries(FuzzServiceTable upnp_static ${LIB_FUZZING_ENGINE})
target_link_libraries(FuzzIxmlDom ixml_static ${LIB_FUZZING_ENGINE})
target_link_libraries(FuzzIxmlOps ixml_static ${LIB_FUZZING_ENGINE})
