list(APPEND UPNP_SOURCES
	upnp/src/api/upnpapi.c
	upnp/src/api/upnpdebug.c
	upnp/src/api/UpnpActionComplete.c
	upnp/src/api/UpnpActionRequest.c
	upnp/src/api/UpnpDiscovery.c
	upnp/src/api/UpnpEvent.c
	upnp/src/api/UpnpEventSubscribe.c
	upnp/src/api/UpnpExtraHeaders.c
	upnp/src/api/UpnpFileInfo.c
	upnp/src/api/UpnpStateVarComplete.c
	upnp/src/api/UpnpStateVarRequest.c
	upnp/src/api/UpnpString.c
	upnp/src/api/UpnpSubscriptionRequest.c
	upnp/src/genlib/client_table/GenlibClientSubscription.c
	upnp/src/genlib/client_table/client_table.c
	upnp/src/genlib/miniserver/miniserver.c
	upnp/src/genlib/net/sock.c
	upnp/src/genlib/net/http/httpparser.c
	upnp/src/genlib/net/http/httpreadwrite.c
	upnp/src/genlib/net/http/parsetools.c
	upnp/src/genlib/net/http/statcodes.c
	upnp/src/genlib/net/http/webserver.c
	upnp/src/genlib/net/uri/uri.c
	upnp/src/genlib/service_table/service_table.c
	upnp/src/genlib/util/list.c
	upnp/src/genlib/util/membuffer.c
	upnp/src/genlib/util/strintmap.c
	upnp/src/genlib/util/util.c
	upnp/src/threadutil/FreeList.c
	upnp/src/threadutil/LinkedList.c
	upnp/src/threadutil/ThreadPool.c
	upnp/src/threadutil/TimerThread.c
	upnp/src/urlconfig/urlconfig.c
	$<$<BOOL:${WIN32}>:upnp/src/inet_pton.c>
	$<$<BOOL:${UPNP_ENABLE_GENA}>:upnp/src/gena/gena_callback2.c>
	$<$<BOOL:${UPNP_ENABLE_GENA}>:upnp/src/gena/gena_ctrlpt.c>
	$<$<BOOL:${UPNP_ENABLE_GENA}>:upnp/src/gena/gena_device.c>
	$<$<BOOL:${UPNP_ENABLE_SOAP}>:upnp/src/soap/soap_common.c>
	$<$<BOOL:${UPNP_ENABLE_SOAP}>:upnp/src/soap/soap_ctrlpt.c>
	$<$<BOOL:${UPNP_ENABLE_SOAP}>:upnp/src/soap/soap_device.c>
	$<$<BOOL:${UPNP_ENABLE_SSDP}>:upnp/src/ssdp/SSDPResultData.c>
	$<$<BOOL:${UPNP_ENABLE_SSDP}>:upnp/src/ssdp/SSDPResultDataCallback.c>
	$<$<BOOL:${UPNP_ENABLE_SSDP}>:upnp/src/ssdp/ssdp_device.c>
	$<$<BOOL:${UPNP_ENABLE_SSDP}>:upnp/src/ssdp/ssdp_ctrlpt.c>
	$<$<BOOL:${UPNP_ENABLE_SSDP}>:upnp/src/ssdp/ssdp_server.c>
	$<$<OR:$<BOOL:${UPNP_ENABLE_GENA}>,
		$<BOOL:${UPNP_ENABLE_OPTIONAL_SSDP_HEADERS}>>:
		upnp/src/uuid/md5.c>
	$<$<OR:$<BOOL:${UPNP_ENABLE_GENA}>,
		$<BOOL:${UPNP_ENABLE_OPTIONAL_SSDP_HEADERS}>>:
		upnp/src/uuid/sysdep.c>
	$<$<OR:$<BOOL:${UPNP_ENABLE_GENA}>,
		$<BOOL:${UPNP_ENABLE_OPTIONAL_SSDP_HEADERS}>>:
		upnp/src/uuid/uuid.c>
	$<$<BOOL:${UPNP_ENABLE_HELPER_API_TOOLS}>:upnp/src/api/upnptools.c>
)

list(APPEND UPNP_HEADERS
	upnp/inc/Callback.h
	upnp/inc/list.h
	upnp/inc/upnp.h
	upnp/inc/UpnpActionComplete.h
	upnp/inc/UpnpActionRequest.h
	upnp/inc/UpnpDiscovery.h
	upnp/inc/UpnpEvent.h
	upnp/inc/UpnpEventSubscribe.h
	upnp/inc/UpnpExtraHeaders.h
	upnp/inc/UpnpFileInfo.h
	upnp/inc/UpnpGlobal.h
	upnp/inc/UpnpInet.h
	upnp/inc/UpnpIntTypes.h
	upnp/inc/UpnpStateVarComplete.h
	upnp/inc/UpnpStateVarRequest.h
	upnp/inc/UpnpStdInt.h
	upnp/inc/UpnpString.h
	upnp/inc/UpnpSubscriptionRequest.h
	upnp/inc/UpnpUniStd.h
	${PUPNP_BINARY_DIR}/upnp/inc/upnpconfig.h
	$<$<BOOL:${UPNP_ENABLE_HELPER_API_TOOLS}>:${PUPNP_SOURCE_DIR}/upnp/inc/upnptools.h>
)

set (UPNP_SOURCES ${UPNP_SOURCES} PARENT_SCOPE)
set (UPNP_HEADERS ${UPNP_HEADERS} PARENT_SCOPE)

if(UPNP_ENABLE_TESTING)
	enable_testing()
	add_subdirectory(test)
endif()
