#ifndef SSDPRESULTDATA_H
#define SSDPRESULTDATA_H

/*!
 * \file
 *
 * \brief Header file for SSDPResultData methods.
 *
 * Do not edit this file, it is automatically generated. Please look at generator.c.
 *
 * \author Marcelo Roberto Jimenez
 */
#include <stdlib.h> /* for size_t */

#include "UpnpGlobal.h" /* for EXPORT_SPEC */

#include "UpnpDiscovery.h"
#include "Callback.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*!
 * SSDPResultData
 */
typedef struct s_SSDPResultData SSDPResultData;

/*! Constructor */
EXPORT_SPEC SSDPResultData *SSDPResultData_new();
/*! Destructor */
EXPORT_SPEC void SSDPResultData_delete(SSDPResultData *p);
/*! Copy Constructor */
EXPORT_SPEC SSDPResultData *SSDPResultData_dup(const SSDPResultData *p);
/*! Assignment operator */
EXPORT_SPEC int SSDPResultData_assign(SSDPResultData *p, const SSDPResultData *q);

/*! SSDPResultData_get_Param */
EXPORT_SPEC const UpnpDiscovery *SSDPResultData_get_Param(const SSDPResultData *p);
/*! SSDPResultData_set_Param */
EXPORT_SPEC int SSDPResultData_set_Param(SSDPResultData *p, const UpnpDiscovery *n);

/*! SSDPResultData_get_Cookie */
EXPORT_SPEC void * SSDPResultData_get_Cookie(const SSDPResultData *p);
/*! SSDPResultData_set_Cookie */
EXPORT_SPEC int SSDPResultData_set_Cookie(SSDPResultData *p, void * n);

/*! SSDPResultData_get_CtrlptCallback */
EXPORT_SPEC Upnp_FunPtr SSDPResultData_get_CtrlptCallback(const SSDPResultData *p);
/*! SSDPResultData_set_CtrlptCallback */
EXPORT_SPEC int SSDPResultData_set_CtrlptCallback(SSDPResultData *p, Upnp_FunPtr n);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* SSDPRESULTDATA_H */

