#ifndef SSDPRESULTDATA_H
#define SSDPRESULTDATA_H

/*!
 * \file
 *
 * \brief Header file for SSDPResultData methods.
 *
 * Do not edit this file, it is automatically generated. Please look at
 * generator.c.
 *
 * \author Marcelo Roberto Jimenez
 */
#include <stdlib.h> /* for size_t */

#include "UpnpGlobal.h" /* for UPNP_EXPORT_SPEC */

#include "Callback.h"
#include "UpnpDiscovery.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*!
 * SSDPResultData
 */
typedef struct s_SSDPResultData SSDPResultData;

/*! Constructor */
UPNP_EXPORT_SPEC SSDPResultData *SSDPResultData_new();
/*! Destructor */
UPNP_EXPORT_SPEC void SSDPResultData_delete(SSDPResultData *p);
/*! Copy Constructor */
UPNP_EXPORT_SPEC SSDPResultData *SSDPResultData_dup(const SSDPResultData *p);
/*! Assignment operator */
UPNP_EXPORT_SPEC int SSDPResultData_assign(
	SSDPResultData *p, const SSDPResultData *q);

/*! SSDPResultData_get_Param */
UPNP_EXPORT_SPEC const UpnpDiscovery *SSDPResultData_get_Param(
	const SSDPResultData *p);
/*! SSDPResultData_set_Param */
UPNP_EXPORT_SPEC int SSDPResultData_set_Param(
	SSDPResultData *p, const UpnpDiscovery *n);

/*! SSDPResultData_get_Cookie */
UPNP_EXPORT_SPEC void *SSDPResultData_get_Cookie(const SSDPResultData *p);
/*! SSDPResultData_set_Cookie */
UPNP_EXPORT_SPEC int SSDPResultData_set_Cookie(SSDPResultData *p, void *n);

/*! SSDPResultData_get_CtrlptCallback */
UPNP_EXPORT_SPEC Upnp_FunPtr SSDPResultData_get_CtrlptCallback(
	const SSDPResultData *p);
/*! SSDPResultData_set_CtrlptCallback */
UPNP_EXPORT_SPEC int SSDPResultData_set_CtrlptCallback(
	SSDPResultData *p, Upnp_FunPtr n);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* SSDPRESULTDATA_H */
