name: lint-clang-format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './upnp ./ixml'
        extensions: 'h,c'
        clangFormatVersion: 11
